apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 448049808628.dkr.ecr.us-east-1.amazonaws.com/node-app:replaceImageTag
        ports:
        - containerPort: 80
